name: Deploy Client Next

on:
  push:
    paths:
      - 'apps/client-next/**'
      - 'packages/ui/**'
      - 'packages/common/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      run: | 
        echo "$SSH_PRIVATE_KEY" > demo.pem
        chmod 600 demo.pem
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i demo.pem ubuntu@ec2-35-94-110-75.us-west-2.compute.amazonaws.com "sudo bash /home/ubuntu/monorepo-deployment/apps/client-next/deploy.sh"