name: Deploy Express Backend

on:
  push:
    paths:
      - 'apps/express-backend/**'
      - 'packages/common/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
      run: |
        ssh-keyscan ec2-35-94-110-75.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts
        echo "$SSH_PRIVATE_KEY" > demo.pem
        chmod 600 demo.pem
        mkdir -p ~/.ssh
        
        ssh -t -i demo.pem ubuntu@ec2-35-94-110-75.us-west-2.compute.amazonaws.com "sudo bash /home/ubuntu/week-12-monorepo-full/apps/express-backend/deploy.sh"